### ISSUE TITLE
UndefVarError: MosekError not defined

### ISSUE THREAD

**Issue by CanLi1** [JuliaOpt/Mosek.jl#137]
Hi,

I'm trying to solve a convex problem using Mosek. My julia version 0.6.1.  I encounter the following error with Mosek. However, the model works well for other solvers like Ipopt.
"
Problem
  Name                   :
  Objective sense        : min
  Type                   : GECO (general convex optimization problem)
  Constraints            : 12397
  Cones                  : 0
  Scalar variables       : 9485
  Matrix variables       : 0
  Integer variables      : 0

Optimizer started.
Presolve started.
ERROR: LoadError: UndefVarError: MosekError not defined
Stacktrace:
 [1] optimize!(::Mosek.MosekMathProgSolverInterface.MosekLinearQuadraticModel) at /home/canl1/.julia/v0.6/Mosek/src/MosekLPQCQPInterface.jl:647
 [2] optimize!(::Mosek.MosekMathProgSolverInterface.MosekNonlinearModel) at /home/canl1/.julia/v0.6/Mosek/src/MosekLPQCQPInterface.jl:1237
 [3] (::Pajarito.#nonlinearcallback#59{Pajarito.PajaritoNonlinearModel})(::Array{Any,1}) at /home/canl1/.julia/v0.6/Pajarito/src/nonlinear_algorithm.jl:583
 [4] optimize!(::Pajarito.PajaritoNonlinearModel) at /home/canl1/.julia/v0.6/Pajarito/src/nonlinear_algorithm.jl:723
 [5] #solvenlp#165(::Bool, ::Function, ::JuMP.Model, ::JuMP.ProblemTraits) at /home/canl1/.julia/v0.6/JuMP/src/nlp.jl:1271
 [6] (::JuMP.#kw##solvenlp)(::Array{Any,1}, ::JuMP.#solvenlp, ::JuMP.Model, ::JuMP.ProblemTraits) at ./<missing>:0
 [7] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/canl1/.julia/v0.6/JuMP/src/solvers.jl:172
 [8] solve(::JuMP.Model) at /home/canl1/.julia/v0.6/JuMP/src/solvers.jl:150
 [9] include_from_node1(::String) at ./loading.jl:576
 [10] include(::String) at ./sysimg.jl:14
 [11] process_options(::Base.JLOptions) at ./client.jl:305
 [12] _start() at ./client.jl:371 
"

Does anyone know how to fix it? Thanks!

**Comment by ulfworsoe** [comment]
I have fixed this in branch `b0.8`. You can try to do
```
Pkg.checkout("Mosek","b0.8")
```
If it works, please let me know.

**Comment by CanLi1** [comment]
Hi,
Thanks for the quick reply. I changed the branch to b0.8 and it now works. 

I also find a minor bug. It would be great if you can fix it. 
I have some constraints like 
a*x + y <=0 
And it report the bug 
ERROR: LoadError: TypeError: msk_nl_getsp_wrapper_mpb: in typeassert, expected Mosek.MosekMathProgSolverInterface.CallbackData, got Array{UInt64,1}
Stacktrace:
 [1] msk_nl_getsp_wrapper_mpb(::Ptr{Void}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Ptr{Bool}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Int32, ::Ptr{Int32}, ::Int32, ::Ptr{Int32}, ::Ptr{Int32}, ::Ptr{Int32}) at /home/canl1/.julia/v0.6/Mosek/src/MosekLPQCQPInterface.jl:898
while loading /home/canl1/work/hierarchy/planning/27/get_fullspace_sol.jl, in expression starting on line 6

After I change it to 
a*x + y <=0.0, 
it works well. I guess maybe you have to input all the constant as Float64 instead of Int32. But most of the users would write constraints like x<=0. It's just a minor issue but it would be great if you can fix it. 

Thanks a lot for your help. 

Best regards,
Can

**Comment by ulfworsoe** [comment]
Hi,

Would it be possible to ask you to make a small example that demonstrates this? It looks simple enough, but I can't figure out how the wrong type ends up in that place.

**Comment by CanLi1** [comment]
Hi,

I could not find a simple example but here's the example I used. It seems to have a type error when I used Mosek.
ERROR: LoadError: TypeError: msk_nl_getsp_wrapper_mpb: in typeassert, expected Mosek.MosekMathProgSolverInterface.CallbackData, got Array{Any,1}
Stacktrace:
 [1] msk_nl_getsp_wrapper_mpb(::Ptr{Void}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Ptr{Bool}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Int32, ::Ptr{Int32}, ::Int32, ::Ptr{Int32}, ::Ptr{Int32}, ::Ptr{Int32}) at /home/canl1/.julia/v0.6/Mosek/src/MosekLPQCQPInterface.jl:898


 If I changed the solver to Ipopt it works well. Thanks a lot!


Here's the code:

using JuMP
using Pajarito
using CPLEX 
using Mosek
using Ipopt
baseprob = [0.3 0.4 0.3]
basedemand = [10.0 8.5  6.0]
basemu = [0.9 1.0 1.1]
baseϕ = [360.0 390.0 420.0]
prob = zeros(Float64, 729)
demand = zeros(Float64, 729)
mu=zeros(Float64, 4, 729)
ϕ =zeros(Float64, 729)
for i1 in 1:3
    for i2 in 1:3
        for i3 in 1:3
            for i4 in 1:3
                for i5 in 1:3
                    for i6 in 1:3
                        temp_scenario = 243 *(i1-1) + 81 *(i2-1) + 27*(i3-1) + 9*(i4-1) + 3*(i5-1) + i6
                        demand[temp_scenario] = basedemand[i1]
                        mu[1, temp_scenario] = basemu[i2]
                        mu[2, temp_scenario] = basemu[i3]
                        mu[3, temp_scenario] = basemu[i4]
                        mu[4, temp_scenario] = basemu[i5]
                        ϕ[temp_scenario] = baseϕ[i6]
                        prob[temp_scenario] =  baseprob[i1] * baseprob[i2] * baseprob[i3] * baseprob[i4] * baseprob[i5] * baseprob[i6]
                    end
                end
            end
        end
    end
end

function generate_fullspace()
    #set up model
    s1 =  Model(solver=PajaritoSolver(rel_gap=0.0001, mip_solver=CplexSolver(), cont_solver=MosekSolver(MSK_IPAR_NUM_THREADS=0)))
    # s1 =  Model(solver=PajaritoSolver(rel_gap=0.0001, mip_solver=CplexSolver(), cont_solver=IpoptSolver()))

    #sets for process
    process = 1:4

    #set for scenarios
    scenarios = 1:729

    #parameters
    Qu = [2.3 2.8  2.0 3.2]
    α = [80.0 100.0 70.0 110.0]
    β =0.3* [90.0 80.0 100.0 72.0]
    ψ = [1.0 1.0 1.0 1.0]
    γ = 2.0*[50.0 50.0 50.0 50.0]


    #first stage variables
    @variable(s1, q[i in process]>=0.0)
    @variable(s1, y[i in process], Bin)

    #second stage variable
    @variable(s1, R[i in process, s in scenarios]>=0.0)
    @variable(s1, P[i in process, s in scenarios]>=0.0)
    @variable(s1, z[i in process, s in scenarios], Bin)
    @variable(s1, δ[s in scenarios]>=0.0 )

    #original constraints in the first stage
    @constraint(s1, e1[i in process], q[i]<= y[i] * Qu[i])

    # Ax+g(y) ⩽0, g2(y)⩽0
    @constraint(s1, c1[i in process, s in scenarios], z[i,s] <= y[i])
    @constraint(s1, c2[i in process, s in scenarios], P[i,s]<= Qu[i] * z[i,s])
    @constraint(s1, c3[s in scenarios], sum(P[i,s] for i in process) == demand[s] - δ[s])
    @NLconstraint(s1, c4[i in process, s in scenarios], -log(1.0+R[i,s])* mu[i,s] + P[i,s] <= 0.0)
    @constraint(s1, c5[i in process, s in scenarios], P[i,s] <= q[i])
    #objective
    @objective(s1, Min, sum(prob[s]*(ϕ[s]*δ[s] + sum(α[i]*y[i]+β[i]*q[i]+γ[i]*z[i,s] + ψ[i] * R[i,s] for i in process)) for s in scenarios  ) )     
    return s1
end


m = generate_fullspace()
stat = solve(m)
println("objective value")
println(getobjectivevalue(m))
println("solver status")
println(stat)
println("First stage varialbes")
println("q:")
println(getvalue(getindex(m, :q)))
println("y:")
println(getvalue(getindex(m, :y)))
println("\nSecond stage varialbes")
println("R:")
println(getvalue(getindex(m, :R)))
println("P")
println(getvalue(getindex(m, :P)))
println("z")
println(getvalue(getindex(m, :z)))
println("δ")
println(getvalue(getindex(m, :δ)))

**Comment by ulfworsoe** [comment]
This is a really unpleasant problem. 

I did manage to reproduce it, but after having run a couple of times it disappeared, and I haven't been able get it again. It seems to be indeterministic, which leads me to think that it may be a garbage collection related issue. I have fixed a bug in the non-linear callback, but I don't know if it addresses the issue.

If you see it again, please post the complete output (if possible), otherwise just the trace. If you can consistently reproduce it, try to insert a line that prints the type (not the value!) of `nlhandle`.

**Comment by CanLi1** [comment]
Thanks for the reply. Should I checkout the package to another branch that you have fixed the bug? I still get the error from time to time.

ERROR: LoadError: TypeError: msk_nl_getsp_wrapper_mpb: in typeassert, expected Mosek.MosekMathProgSolverInterface.CallbackData, got Array{Any,1}
Stacktrace:
 [1] msk_nl_getsp_wrapper_mpb(::Ptr{Void}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Ptr{Bool}, ::Ptr{Int32}, ::Ptr{Int32}, ::Int32, ::Int32, ::Ptr{Int32}, ::Int32, ::Ptr{Int32}, ::Ptr{Int32}, ::Ptr{Int32}) at /home/canl1/.julia/v0.6/Mosek/src/MosekLPQCQPInterface.jl:898

I'm wondering how many times do you rerun the code so that this can disappear. What is `nlhandle` ? Can you give an example of printing the type of nlhandle?

Thanks a lot for your help.

Best,
Can

**Comment by ulfworsoe** [comment]
It should be enough to update branch `b0.8`.

Sorry, I should have been a bit more specific. In Mosek.jl in `src/MosekLPQCQPInterface.jl` insert a line before line 980, so it looks like this:
```
    cb_tmp = unsafe_pointer_to_objref(nlhandle)
    println("Type of cb = $(typeof(cb))")
    cb = cb_tmp::CallbackData
```

On the original code without modifications to `Mosek.jl` i managed to get the error several times, but with slightly different message. Having modified the code I could not reproduce it, and I still haven't figured out what the problem was/is.
